### ISSUE TITLE
Weird Scroll Behavior on Android

### ISSUE THREAD

**Issue by infosisio** [standardnotes/mobile#80] opened 2018-08-16 18:32 UTC
When editing a note on Android I am some times not able to scroll up to the start of the note. 

If I go back and reopen the note, it starts from the top normally. 

This is exactly the issue: https://github.com/standardnotes/mobile/issues/26

@mobitar Do you suspect what it could be ? 

Android version 7 here.

**Comment by infosisio** [comment] 2018-08-16 22:25
This is exactly the issue: https://github.com/standardnotes/mobile/issues/26

@mobitar Have you found the cause ? Android version 7 here.

**Comment by infosisio** [comment] 2018-08-18 03:58
@mobitar Can you reproduce this ? It is quite annoying once a user realizes it.

**Comment by infosisio** [comment] 2018-08-18 15:28
@mobitar I just noticed that keyboardDismissMode is missing for Android. Is that the cause ?

**Comment by infosisio** [comment] 2018-08-18 17:00
@mobitar I noticed that the TextInput for Android has nk keyboardDismissMode='on-drag'

**Comment by mobitar** [comment] 2018-08-19 00:53
Not sure, need to investigate it more. I'll queue this up for when I'm back on mobile.

**Comment by infosisio** [comment] 2018-08-21 21:26
@mobitar I believe I have fixed this by using: https://facebook.github.io/react-native/docs/keyboardavoidingview

**Comment by mobitar** [comment] 2018-08-22 14:27
On Android we use a native text component called the SNTextView, which is bundled with the app, and can be edited on the Java side. If you want to toy around with this more, might want to begin your investigation there..

**Comment by infosisio** [comment] 2018-08-22 14:29
@mobitar Do you have any ideas for how to fix this ? I don't think it's within my range of skills.

**Comment by mobitar** [comment] 2018-08-22 14:44
No idea. Would need to investigate deeply. It's on my list, but working through a few other things at the moment.

**Comment by infosisio** [comment] 2018-08-23 02:30
@mobitar Regardless of dealing directly with that issue, isn't the p

**Comment by infosisio** [comment] 2018-08-23 02:32
@mobitar By the way, regardless of directly dealing with the height of the container etc, isn't the right behavior to dismiss the keyboard when the user tries to scroll ? That is what most apps do.

**Comment by mobitar** [comment] 2018-08-23 14:16
Is that how it's done on Android? I'd have to double check. On iOS, sometimes you just want to scroll while you're editing. It requires a firm scroll down to dismiss the keyboard interactively.

**Comment by mobitar** [comment] 2018-08-24 14:16
I'll have to upgrade React Native in the app at some point. A scary operation though, given stability is not guaranteed.

**Comment by infosisio** [comment] 2018-08-29 23:15
@mobitar Have you been able to play with this so far ? No pressure or anything, just can't wait to see it gone xD

**Comment by mobitar** [comment] 2018-08-30 03:42
Like I said, have other things I’m working on right now. Would update this
thread if I did.

On Aug 23, 2018, at 11:20 AM, infosisio <notifications@github.com> wrote:

@mobitar <https://github.com/mobitar> I've just seen this in many apps and
read online when checking out for solution, for instance:
"Another common issue I have run into is the keyboard would be up while
scrolling through a page.

Tapping and dismissing it is not the ideal solution for a seamless
experience.

Luckily, React Native team has a fix for this."

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/standardnotes/mobile/issues/80#issuecomment-415477739>,
or mute the thread

**Comment by infosisio** [comment] 2018-08-30 04:42
@mobitar I fully understand that; it wasn't a request, or even a question if this is done, was just poking you because I was curious if you had any news on it.

**Comment by mobitar** [comment] 2018-08-30 14:51
I appreciate you @infosisio. You've definitely helped find some good issues and did some deep investigations into them. But I have a system for keeping track of these issues, and following up many times on the same issue really adds to the stress overload for me in terms of email notifications. But, hoping to investigate this soon in any case.

**Comment by mobitar** [comment] 2018-08-30 17:44
No worries at all! (I feel bad myself for having even made this into any sort of deal; should be my burden to bear, not yours ;)

**Comment by infosisio** [comment] 2018-10-09 18:20
@mobitar I am sorry to ask again but it's been a really long time and I haven't heard anything about this issue which is critical to mobile functionality.

**Comment by mobitar** [comment] 2018-10-10 14:22
I haven't been able to reproduce this issue when I last went in. I work on mobile in bursts so I'll check this out in the next burst. Can't really give a date though.

**Comment by infosisio** [comment] 2018-10-16 22:58
@mobitar I saw the latest commit. Is it a fix ? :D

**Comment by mobitar** [comment] 2018-10-23 17:06
Looked into this issue, and it appears to be related to having the keyboard displayed while adding new lines. Also happens when keyboard is dismissed and remote content updates comes in. Tried fixing, but no luck yet. Will have to revisit in the coming weeks.

**Comment by mobitar** [comment] 2019-01-29 15:18
We'll track this issue here: https://github.com/standardnotes/mobile/issues/130

**Closed by mobitar** 2019-01-29 15:18 UTC
