### ISSUE TITLE
Android 10: sorting by date added reverts itself to date modified

### ISSUE THREAD

**Issue by bipox** [standardnotes/mobile#323] opened 2020-11-17 12:24 UTC
If I restart the app again nothing changes, but if I don't open it for a few hours the setting reverts to "date added"

**Comment by JaspalSuri** [comment] 2020-11-17 13:25
Hi @bipox,

Thanks for the report. What version of the app are you using? 

Can you share what device you're using and what version of Android is running as well?

**Comment by bipox** [comment] 2020-11-17 13:34
When I wrote the report I was still on 3.5.7. I saw the update after (I didn't edit the post since there's no mention of this issue in the changelog). 
APK from Github. 

Android 10, Lenovo P2. No Google services.

**Comment by JaspalSuri** [comment] 2020-11-18 12:19
Thank you so much for that info! I've passed it along to our mobile dev for further review.

**Comment by JaspalSuri** [comment] 2020-11-18 12:27
It looks like there were no logs available. I also wasn't able to reproduce this issue, yet, I'm afraid. I hope that the latest update resolves this! 

If you have an account with us and have confirmed that your password works and everything on your account is current by logging into our [web app](https://app.standardnotes.org/), then it might be worth logging out of the Android app and clearing its cache and storage data before logging in again as a potential remedy to this issue.

**Comment by radko93** [comment] 2020-11-18 12:31
@bipox do you have a passcode set? Do you have it set as "immediate"?

**Comment by bipox** [comment] 2020-11-18 16:45
> It looks like there were no logs available. 

I honestly thought you guys didn't use trackers. I remember the privacy statement saying there weren't any.

I have a paid account, everything else works (linux desktop client, webapp)


> @bipox do you have a passcode set? Do you have it set as "immediate"?

no passcode on Android

But I have the app on iOS (forgot about it, I don't use it) with password to open it.
After I hit "submit" the button stays grey and nothing happens.

**Comment by JaspalSuri** [comment] 2020-11-18 17:16
> I honestly thought you guys didn't use trackers. I remember the privacy statement saying there weren't any.

We use Bugsnag as an error monitoring tool to receive copies of errors reported by the app, not track what the user is doing within the app at all times. It's anonymized and noninvasive. You can read more on our [use of Bugsnag here](https://github.com/standardnotes/forum/issues/1129).

> I have a paid account, everything else works (linux desktop client, webapp)

Thanks for letting me know and thanks for supporting us by subscribing to Extended! I would suggest reinstalling the iOS app and clearing out the Android app's storage, and then logging in again.

**Comment by bipox** [comment] 2020-12-01 18:56
Same problem reappeared, it goes back to date added.

It goes further, I have access to themes and extensions but I am in fact disconnected. 
It says in settings "Sign out (undefined)", and everything I entered since the bug appeared hasn't been synchronized.
This happened last time too.

**Comment by JaspalSuri** [comment] 2020-12-03 10:13
> Same problem reappeared, it goes back to date added.

I'm sorry to hear that. I'm afraid that we still can't reproduce this issue. 

> It says in settings "Sign out (undefined)", and everything I entered since the bug appeared hasn't been synchronized.

I'm sorry to hear that it's happened again. Please make the changes were made on the Android app on to the [web](app.standardnotes.org) or desktop app and then sign out and clear the Android app's storage & cache (again). Locate the app in the app drawer, press and hold the app's icon, tap on **App Info**, and then locate the settings/buttons pertaining to deleting the app's **storage & cache**. From there you should be able to relaunch the app and sign in again. This has helped most users.

**Comment by radko93** [comment] 2020-12-21 18:05
@bipo we released a new update with a fix related the issue you are having, please try it and let me know!

**Comment by bipox** [comment] 2020-12-21 18:47
@radko93 Thanks for fixing this. 

I will tell if the problem reappears, but it hasn't since my last report 20 days ago.

**Comment by radko93** [comment] 2020-12-21 19:14
I will close this issues for now then, I can reopen if the issue comes back.

**Closed by radko93** 2020-12-21 19:14 UTC
