### ISSUE TITLE
Mobile login - need to trim user email input whitespaces..

### ISSUE THREAD

**Issue by Nik-olo** [standardnotes/mobile#278] opened 2020-09-03 23:22 UTC
This happened when I tried to login. I did not understand why I was getting an error. I am using a password manager to enter the email and password and there was a whitespace in the end of the email address.

iOS app (v3.0.23)

solution: The whitespace could be trimmed on signin on app? 

![Image of bug](https://i.imgur.com/EOaStnD.png)

**Comment by JaspalSuri** [comment] 2020-09-04 08:20
Hi @Nik-olo,

Thank you for highlighting this issue! I apologize for the inconveniences caused by the trailing white space. I'll pass this along to the team for further review. 🙂

**Comment by radko93** [comment] 2020-12-14 10:33
Thank you for the report, this should be fixed in the latest version.

**Closed by radko93** 2020-12-14 10:33 UTC
