### ISSUE TITLE
Can’t decrypt on iOS14.1/v3.5.8(30)

### ISSUE THREAD

**Issue by cal-moh** [standardnotes/mobile#321] opened 2020-11-17 05:43 UTC
Problem - SN v3.5.8(30) on iOS14.1 cannot decrypt notes. The same account works on Windows (v3.4.10) and iOS12.4.8(v3.0.17). 

Steps to reproduce:

1. Windows auto upgraded encryption in the latest v3.5 beta auto update
2. iOS couldn’t access notes beginning late October
3. Accessed with TestFlight and tried all versions - did not work
4. Exported notes on windows version to an offline zip without encryption, and Uninstalled old Windows app. 
5. Created fresh account and imported notes to lower Windows version (v3.4.10). 
6. iOS 12.4.8 device could access notes from fresh account 
7. iOS 14.1 device still cannot access notes from fresh accounts (stuck on “Missing Keys: Please sign in to restore your decryption keys and notes”). Multiple uninstalls, reinstalls, version changes, old accounts/new accounts iterations tried

**Comment by JaspalSuri** [comment] 2020-11-17 11:07
Hi @cal-moh,

This is interesting and helpful info, thank you for taking the time to resolve the issue on your own! 

I would suggest that on step five, when you create an a new account, log into the [latest desktop](http://standardnotes.org/download/) or [web app](https://app.standardnotes.org/) instead and import your encrypted backup into the new account (on the latest versions of the web/desktop clients). 

From there you can [reset](http://standardnotes.org/reset) the account that you've recently created (or the older one, after you've confirmed that the newer one fully works with FileSafe, or any other features that you're using) with the [reset tool](http://standardnotes.org/reset).

Please let me know how that goes and if you have any other questions.

**Comment by cal-moh** [comment] 2020-11-18 15:13
Thanks @JaspalSuri - this has worked beautifully. I have now moved all three installed instances - iOS 12.4.8, iOS 14.1, and Windows instances, to the latest available versions. Should I let this issue stay open, if another kind of fix is needed, or should I close it, given that atleast one kind of fix exists?

**Comment by JaspalSuri** [comment] 2020-11-18 16:42
You're most welcome, @cal-moh! I'm happy to hear that. Thank you so much for doing so. We personally don't mind whether the issues are opened or closed as they can be re-opened at any time and we want everyone to provide their input of any potentially recurring issues, but I'll go ahead and close this since we're handling things on a case-by-case basis.

**Closed by JaspalSuri** 2020-11-18 16:42 UTC
