### ISSUE TITLE
Can’t paste in iOS

### ISSUE THREAD

**Issue by kevquirk** [standardnotes/mobile#332] opened 2020-11-30 23:13 UTC
Title says it all really. Trying to paste a url into markdown pro editor but it never gives me the option to paste. No matter how much I tap on the screen, no paste dialogue appears. There's also no past icon above the keyboard.

I have to login to the webui to paste.

iOS version: iPad OS 14.2
Standard notes version: 3.5.10

**Comment by kevquirk** [comment] 2020-11-30 23:15
Note: this only affects the markdown pro editor. I can successfully paste if I flip to the plain editor.

**Comment by JaspalSuri** [comment] 2020-12-01 06:28
Hi @kevquirk,

I'm sorry to hear that. We'll look into this and get back to you ASAP. We thought it was fixed in version 3.5 as we were unable to reproduce it in the internal betas. I currently cannot reproduce this on an iPhone, but we'll have someone test it on an iPad.

**Comment by kevquirk** [comment] 2020-12-01 07:01
Yeah, just tested it on my iPhone and it's fine. Looks to be iPad specific. Thanks.

**Comment by JaspalSuri** [comment] 2020-12-01 10:38
Thank you for doing that! It looks like you won't have to restart your iPad, as someone from the support team was able to reproduce the issue. It's been passed along to our mobile dev for further review. 🙂

**Comment by kevquirk** [comment] 2020-12-01 13:15
Perfect. Thank you! :-)

**Comment by JaspalSuri** [comment] 2020-12-02 09:11
Just a minor update: we're looking into this further to confirm whether it's an issue with the app or the editor.

**Comment by JaspalSuri** [comment] 2021-04-03 00:30
Hi @kevquirk,

I haven't been able to reproduce this issue on my iPad so I am going to close this thread. Please let me know if you can still reproduce this issue or have any questions and/or feedback. 🙂

**Closed by JaspalSuri** 2021-04-03 00:30 UTC
