### ISSUE TITLE
Fascinating - faster on iPhone, Much slower on 'droid

### ISSUE THREAD

**Issue by SchuylerThompson** [standardnotes/mobile#101] opened 2018-11-14 22:11 UTC
I've switched from Evernote to Standard - thank you all for the work that you've done, it's truly outstanding.
I use an iPhone 8Plus for work and a Huawei P10 for personal with Standard Notes on both, ~950 notes on both of them.  When I start the app on the iPhone it opens and decrypts blisteringly fast compared to the 'droid, where it'll sit there for almost five minutes, counting up the notes until they're all fully loaded.  If I disable encryption on the 'droid (file system encrypted by default anyway), it makes no difference.
I understand that it's the same base code on each - the P10 is no slouch, why is the load time on the two platforms so very different?  Can anything be done?

         ST

**Comment by mobitar** [comment] 2018-11-15 16:20
Hey @SchuylerThompson, that's bizarre. I've heard this issue from one other person. However, it has been tricky in that I haven't been able to replicate it. It works equally fast for me on both iOS and Android. I honestly don't have any clues right now. At this point I've yet to determine if it's account related or device related. Do you have any other Android phones around that you can test the same account on?

**Comment by SchuylerThompson** [comment] 2018-11-15 23:30
I sure can, I'll need some time but I can find another device, load up my account and see how it behaves.  Thank you for the response!

  ST

**Comment by mobitar** [comment] 2018-11-19 16:12
Works fine on my 3 Android devices. Still need to determine whether it's account related or device related.

**Comment by Riotous** [comment] 2018-11-19 17:04
@mobitar It's not that the app is SLOW on Android. Many people would say the Android app is fine. However, compared to the iPhone app, especially on startup, it's slower. You'd expect a note app to launch faster than it does on Android. I'd just like the Android app to run faster. It should launch much faster than it does right now.

**Comment by mobitar** [comment] 2018-11-20 15:45
In this case, the issue I'm referring to is where startup can take > 10 seconds. That shouldn't be the case. In my tests the Android app runs as fast, if not faster, than the iPhone app. There's just some localized issue with startup speed affecting some users.

**Comment by mobitar** [comment] 2018-11-25 16:54
I’ve created a dummy account with 1065 notes. I’ve tested on my Pixel 3, and it loads up from a fresh start blazingly fast, no more than 2-3 seconds. I'd be grateful if you guys tried signing in to this account on your devices and report load time on fresh app start.

The account is:
email: **android-test@standardnotes.org**
password: **password**

**Comment by Riotous** [comment] 2018-11-25 17:48
@mobitar I'm not seeing a startup over 10 seconds at all but I am seeding a delayed startup even when no account is being used. The white screen that appears before the app loads feels like it shouldn't be there.

**Comment by morewithout** [comment] 2018-12-17 17:19
Hi, 

I'm using a Lenovo Moto G4 with Android 7.0

First load of android-test takes 45s (i.e to download all the notes). Subsequent opening of the app after closing it takes 19s (i.e. to decrypt all the locally stored notes). I would class this is as a bit slow but acceptable.

However. My own notes collection comprises 1,108 notes. First load takes 1m08s. Subsequent opening of the app after closing takes a whopping 3m25s which is practically unusable (and 3 times longer than it took to download the notes first time around).

I noticed that decrypting gets progressively - and geometrically - slower. The first 100 notes decrypt quickly. By 500 notes it's taking noticeably longer and the final few hundred from 800 onwards seem to account for more than half the total time. So I'm guessing some cumulative problem?

I've tried turning off local encryption but it made no discernible difference. So I guess the problem is not decrypting per se, but rather some cumulative overhead in refreshing the view as each note is loaded?

I really hope you can find and fix this as it's making an otherwise fine app practically unusable. I'm happy to help in any way I can (but I'm no Android coder).

Thanks in anticipation.

**Comment by morewithout** [comment] 2018-12-17 18:20
p.s. All my notes are tagged. One of the tags contains 789 notes. I'm afraid I can't share the data with you as the 789 comprise my personal journal of several years.

**Comment by morewithout** [comment] 2018-12-17 21:43
Deleting the tag that contained 789 notes worked around the problem. Now loads in 17s for the same 1,108 notes but without that tag. Any chance of being able to easily tag multiple items once this problem is fixed properly? :-/ (e.g. select all items that have no tag and then apply a tag to the selection)

**Comment by mobitar** [comment] 2018-12-18 19:11
Oh wow, good to know. Yeah, I'm starting to suspect it might be something to do with resolving relationships between notes and tags. Hoping to investigate this after I finish up on the upcoming desktop release.

**Comment by dpenic** [comment] 2019-01-02 13:53
@mobitar Having the same problem, loading ~1500 notes on a Google Pixel takes around 45s. They are also heavily tagged (+ using Quick Tags extension on a desktop version).

**Comment by mobitar** [comment] 2019-01-02 16:12
Yeah, the issue is to do with having a tag that may have several hundred notes. I'm currently working on a big mobile update and it should also include a fix to this. No timeline yet, but probably in the range of a month or so.

**Comment by mobitar** [comment] 2019-01-15 02:41
This issue should be fixed in the 3.0 beta. Please give it a run here and see if that helps: https://play.google.com/apps/testing/com.standardnotes

**Closed by mobitar** 2019-01-15 02:41 UTC

**Comment by dpenic** [comment] 2019-01-15 08:33
Installed the beta version and can confirm that the issue is fixed. Loads all notes in ~5 seconds. Thank you!
